Add Coherence based caching implementation for Micronaut
micronaut-projects/micronaut-coherence pull request #18
Opened 2021-01-26 14:31 UTC by vasac

2021-02-02 18:01 UTC, aseovic requested changes
Looks good, but there are some minor changes to be made in async cache implementation, to offload response processing from a service thread to an executor service thread.

We also need to discuss and decide if the caches should be user-managed, as is the case now, or system-managed and defined in our system cache config.

2021-02-02 18:18 UTC, aseovic commented on coherence-cache/src/main/java/io/micronaut/cache/coherence/CoherenceCacheManager.java
> +        NamedCache<Object, Object> nativeCache = session.getCache(name);
We should allow users to configure a `coherence.caching.prefix` prefix that will be used for all cache names, and will be blank by default.

2021-02-03 09:25 UTC, alvarosanchez commented on coherence-cache/build.gradle
> +    api "com.oracle.coherence.ce:coherence"
Is the idea of `compileOnly` that users can choose between community and enterprise editions? If so, when this is integrated in Micronaut Launch, you would need to create 2 different features that add the correct dependency in each case

2021-02-03 15:40 UTC, vasac commented on coherence-cache/build.gradle
> +    api "com.oracle.coherence.ce:coherence"
Yeah, we'll add Coherence dependency too in Micronaut Launch.

2021-02-03 15:41 UTC, vasac commented on coherence-cache/src/main/java/io/micronaut/cache/coherence/CoherenceCacheManager.java
> +        NamedCache<Object, Object> nativeCache = session.getCache(name);
Left this as it is as `micronaut-cache` test checks whether provided cache name matches requested cache name.

2021-02-03 15:44 UTC, vasac commented on coherence-cache/src/main/java/io/micronaut/cache/coherence/CoherenceAsyncCache.java
> + * A {@link io.micronaut.cache.SyncCache} implementation based on Coherence.
Fixed.

2021-02-03 15:44 UTC, vasac commented on coherence-cache/src/main/java/io/micronaut/cache/coherence/CoherenceAsyncCache.java
> +     * @param executorService   managers the pool of executors
Fixed.

2021-02-03 15:44 UTC, vasac commented on coherence-cache/src/main/java/io/micronaut/cache/coherence/CoherenceAsyncCache.java
> +        return get(key, requiredType).thenApply(existingValue -> {
Fixed.

2021-02-03 15:45 UTC, vasac commented on coherence-cache/src/main/java/io/micronaut/cache/coherence/CoherenceAsyncCache.java
> +        asyncCache.get(key).whenComplete((response, throwable) -> {
Fixed.

2021-02-03 15:45 UTC, vasac commented on coherence-cache/src/main/java/io/micronaut/cache/coherence/CoherenceAsyncCache.java
> +        return asyncCache.putIfAbsent(key, value).thenApply(existingValue -> {
Fixed.

2021-02-03 15:45 UTC, vasac commented on coherence-cache/src/main/java/io/micronaut/cache/coherence/CoherenceAsyncCache.java
> +        asyncCache.put(key, value).whenComplete((response, throwable) -> {
Fixed.

2021-02-03 15:45 UTC, vasac commented on coherence-cache/src/main/java/io/micronaut/cache/coherence/CoherenceAsyncCache.java
> +        asyncCache.clear().thenRun(() -> future.complete(true));
Fixed.

2021-02-03 15:45 UTC, vasac commented on coherence-cache/src/main/java/io/micronaut/cache/coherence/CoherenceSyncCache.java
> + * A {@link AsyncCache} implementation based on Coherence.
Fixed.

2021-02-03 15:46 UTC, vasac commented on coherence-cache/src/main/java/io/micronaut/cache/coherence/CoherenceAsyncCache.java
> +        asyncCache.remove(key).whenComplete((response, throwable) -> {
Fixed.

2021-02-03 21:58 UTC, aseovic approved these changes
LGTM

2021-02-03 21:59 UTC, merged